language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: python hello_tests.py
deploy:
  provider: heroku
  api_key:
    secure: PKuREQ0ecPHwiHdgbfS9KDMCoQYxuJwtfapv9zYSwxa2Pwk1NswR+tNGuzjlNxCm4tDgQYAT22uqnxju91xav0S+eDBcCzxby0aoQnYcBhyIIZvLhsjjuXJAQ3fBVYhi007A43cdAsmVdG+Xw2NucL1i/7HpLfq6X3aA1cgUbe8=
  app: ancient-headland-6650
  on:
    repo: chrisheaththomas/hello-world
