language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: python hello_tests.py
deploy:
  provider: heroku
  api_key:
    secure: KqD1HCETnBpXQZbBPczLfYODmZT8o4CxqEhDkhJqsPbswTNuCh/MN1iUbnxpmnZkA/RY2rH8hhYV522Fda0Ka7Blfc3OhsCA7fNQstFBU5lKAgn7aDyh8gRimRdeIJCBk/eadp28pEG2CMUAXncXl1gkJAnv3NujwnHySy/pbv8=
  app: ancient-headland-6650
  on:
    repo: chrisheaththomas/hello-world
