language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: python hello_tests.py
deploy:
  provider: heroku
  api_key: 16bf79ce-b1e3-4010-96a1-5c94aa872513
  app: ancient-headland-6650
  on:
    repo: chrisheaththomas/hello-world
